### ISSUE TITLE
Appium Maven Test file inside React Native project.

### ISSUE THREAD

**Issue by suvro24** [TomSoderling/VSAppCenter#1]
I would like to know how can I build my Appium Test file using Maven part of React Native Android Build. I would to build my maven project which contains the Appium test case and then run those test in appcenter using post build script. I was able to prepare and upload my Appium test from locallly using appcenter CLI. Now I want to prepare my Appium test file  as part of CI/CD and run those test using post build script. How can i do that?

Thank you.

**Comment by TomSoderling** [comment]
Whoa, no idea. I've never done a React Native Android Build. My best advice is to use the chat feature inside the VS App Center website to get in touch with App Center support. They've been really responsive and helpful. Good luck!
